version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - 'SA_PASSWORD=YourSecretPa$$W0rD'
    ports:
      - 1433:1433
    volumes:
      - shared-data:/var/opt/mssql/backup

  testdbs:
    depends_on:
        - mssql
    build:
      context: .
      dockerfile: ./Support/mssql.dockerfile
    environment:
      - 'SA_PASSWORD=YourSecretPa$$W0rD'
    command: /app/init.sh
    volumes:
      - shared-data:/var/opt/mssql/backup
    
volumes:
  shared-data:
